config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  resources :tasks
  root 'tasks#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
  end

  resources :labels

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  validates :name, presence: true, length: { maximum:15 }

  has_many :labellings, dependent: :destroy
  belongs_to :user
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings

  validates :task_name, presence: true, length: { maximum:30 }
  validates :content, presence: true
  validates :deadline, presence: true
  validates :priority, presence:true
  validates :status, presence:true

  enum status: %i[未着手 着手中 完了]
  enum priority: %i[高 中 低]

  scope :name_search, -> task_name {
    next if task_name.blank?
    where("task_name LIKE ?", "%#{task_name}%")
  }

  scope :status_search, -> status {
    next if status.blank?
    where(status: status)
  }

  scope :label_search, -> label {
    next if label.blank?
    where(id: Labelling.where(label_id: label).pluck(:task_id))
  }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }
  before_validation { email.downcase! }

  before_destroy :last_admin_not_delete
  before_update :last_admin_not_change

  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy

  has_secure_password

  def last_admin_not_delete
    throw(:abort) if User.where(admin: true).length == 1 && self.admin?
  end

  def last_admin_not_change
    if User.where(admin: true).length == 0
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_admin
  def index
    @users = User.select(:id, :name, :email, :admin, :created_at, :updated_at).page(params[:page]).per(5).order(id: "ASC")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を更新できません。"
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path
      flash[:notice] = "ユーザー「#{@user.name}」を削除しました。"
    else
      redirect_to admin_users_path
      flash[:notice] = "ユーザーを削除できません"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end


  def check_admin
    raise Forbidden unless logged_in? && current_user.admin?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :basic_authentication, if: :production?

  private

  def production?
   Rails.env.production?
  end

  def basic_authentication
    authenticate_or_request_with_http_basic do |name, password|
      name == 'admin' && password == 'admin_password'
    end
  end

  class Forbidden < ActionController::ActionControllerError
  end

  rescue_from Forbidden, with: :rescue403

  private
    def rescue403(e)
      @exception = e
      render template: 'errors/forbidden', status: 403
    end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_params, only: [:edit, :destroy, :update]
  before_action :display_limit
  def index
    @labels = current_user.labels
  end

  def new
    @label = Label.new
  end

  def create
    @label = current_user.labels.build(label_params)
    if @label.save
      redirect_to labels_path, notice: "ラベルを作成しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @label.update(label_params)
      redirect_to labels_path, notice: "ラベルを更新しました"
    else
      redirect_to labels_path, notice: "ラベルを更新できません"
    end
  end

  def destroy
    @label.destroy
    redirect_to labels_path, notice: "ラベルを削除しました。"
  end

  private

  def label_params
    params.require(:label).permit(:name, :created_at, :updated_at)
  end

  def set_params
    @label = Label.find(params[:id])
  end

  def display_limit
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :display_limit

  PER = 10

  def index
    if params[:search]
      @tasks = current_user.tasks.name_search(params[:task_name])
                           .status_search(params[:status])
                           .label_search(params[:label_id])
                           .page(params[:page]).per(PER)
    elsif params[:sort_deadline]
      @tasks = current_user.tasks.page(params[:page]).per(PER).order(deadline: "DESC")
    elsif params[:sort_priority]
      @tasks = current_user.tasks.page(params[:page]).per(PER).order(priority: "ASC")
    else
      @tasks = current_user.tasks.page(params[:page]).per(PER).order(id: "DESC")
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to task_path(@task.id), notice: "タスクを作成しました"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice:"タスクを削除しました"
  end

  private

  def task_params
    params.require(:task).permit(:task_name, :content, :deadline, :status, :priority, label_ids: [])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def display_limit
    redirect_to new_session_path unless logged_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :dont_user_new, only: [:new]
  before_action :check_user, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to tasks_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def dont_user_new
    redirect_to tasks_path if logged_in?
  end

  def check_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to tasks_path,notice:"権限がありません"
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def login(user)
    session[:user_id] = user.id
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2><%= t('view.user_edit') %></h2>
<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <%= f.label :name %>
  <p><%= f.text_field :name %></p>

  <%= f.label :email %>
  <p><%= f.email_field :email %></p>

  <%= f.label :admin %>
  <%= f.check_box :admin %></p>

  <%= f.label :password %>
  <p><%= f.password_field :password %></p>

  <%= f.label :password_confirmation %>
  <p><%= f.password_field :password_confirmation %></p>

  <%= f.submit t('view.user_update') %>
<% end %>

<%= link_to t('view.index'), admin_users_path %>

app/views/admin/users/index.html.erb
<h2><%= t('view.user_index') %></h2>
<%= link_to t('view.new'), new_admin_user_path, class: "btn btn-primary" %>

<table>
  <tr>
    <th class= 'th_user_name'><%= t('view.name') %></th>
    <th class= 'th_email'><%= t('view.email') %></th>
    <th class= 'th_admin'><%= t('view.admin') %></th>
    <th class= 'th_tasks_count'><%= t('view.tasks_count') %></th>
    <th class= 'th_created_at'><%= t('view.created_at') %></th>
    <th class= 'th_updated_at'><%= t('view.updated_at') %></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.admin? ? "有" : "無" %></td>
    <td><%= user.tasks.count %></td>
    <td><%= user.created_at.strftime('%Y-%m-%d') %></td>
    <td><%= user.updated_at.strftime('%Y-%m-%d') %></td>
    <td><div class="alert alert-warning" role="alert"><%= link_to t('view.show'), admin_user_path(user.id), class: "alert-link" %></div></td>
    <td><div class="alert alert-info" role="alert"><%= link_to t('view.edit'), edit_admin_user_path(user.id), class: "alert-link" %></div></td>
    <td><div class="alert alert-danger" role="alert"><%= link_to t('view.delete'), [:admin, user], class: "alert-link",  method: :delete ,data: { confirm: "本当に削除してもよろしいですか？" } %></td>
  </tr>
<% end %>
</table>
<%= paginate @users %>

app/views/admin/users/new.html.erb
<h2>ユーザー登録</h2>
<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <%= f.label :name %>
  <p><%= f.text_field :name %></p>

  <%= f.label :email %>
  <p><%= f.email_field :email %></p>

  <%= f.label :admin %>
  <%= f.check_box :admin %></p>

  <%= f.label :password %>
  <p><%= f.password_field :password %></p>

  <%= f.label :password_confirmation %>
  <p><%= f.password_field :password_confirmation %></p>

  <%= f.submit t('view.user_new') %>
<% end %>

<%= link_to t('view.user_index'), admin_users_path %>

app/views/admin/users/show.html.erb
<h2><%= @user.name %></h2>

<%= t('view.email')%>
<%= @user.email %>

<table>
  <tr>
    <th class= 'th_task_name'><%= t('view.task_name') %></th>
    <th class= 'th_content'><%= t('view.content') %></th>
    <th class= 'th_created_at'><%= t('view.created_at') %></th>
    <th class= 'th_deadline'><%= t('view.deadline') %></th>
    <th class= 'th_status'><%= t('view.status') %></th>
    <th class= 'th_priority'><%= t('view.priority') %></th>
  </tr>

<% @user.tasks.each do |task| %>
  <tr>
    <td><%= task.task_name %></td>
    <td><%= task.content %></td>
    <td><%= task.created_at.strftime('%Y-%m-%d') %></td>
    <td><%= task.deadline.strftime('%Y-%m-%d') %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
  </tr>
<% end %>
</table>

<%= link_to t('view.user_index'), admin_users_path %>

app/views/labels/edit.html.erb
<h2><%= t('view.label_edit') %></h2>
<%= form_with(model: @label, local: true) do |f| %>

  <%= f.label :name %>
  <p><%= f.text_field :name %></p>

  <%= f.submit t('view.label_update') %>
<% end %>

<%= link_to t('view.label_index'), labels_path %>

app/views/labels/index.html.erb
<h2>ラベル一覧</h2>
<%= link_to "ラベル作成", new_label_path, class: "btn btn-primary" %>
<%= link_to "タスク一覧", tasks_path, class: "btn btn-primary" %>
<table>
  <tr>
    <th class= 'th_label_name'><%= "ラベル名" %></th>
    <th class= 'th_created_at'><%= t('view.created_at') %></th>
    <th class= 'th_updated_at'><%= t('view.updated_at') %></th>
  </tr>

<% @labels.each do |label| %>
  <tr>
    <td><%= label.name %></td>
    <td><%= label.created_at.strftime('%Y-%m-%d') %></td>
    <td><%= label.updated_at.strftime('%Y-%m-%d') %></td>
    <td><div class="alert alert-info" role="alert"><%= link_to t('view.edit'), edit_label_path(label.id), class: "alert-link" %></div></td>
    <td><div class="alert alert-danger" role="alert"><%= link_to t('view.delete'), label_path(label.id), class: "alert-link",  method: :delete ,data: { confirm: "本当に削除してもよろしいですか？" } %></td>
  </tr>
<% end %>
</table>

app/views/labels/new.html.erb
<%= form_with(model: @label, local:true) do |f| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <h2><%= @label.errors.count %><%= t('view.error_number') %></h2>
      <ul>

      <% @label.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2><%= t('view.labels_new') %></h2>

  <%= f.label :name %>
  <p><%= f.text_field :name %></p>

  <%= f.submit t('view.label_new') %>
<% end %>

<%= link_to t('view.label_index'), labels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manyo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header clearfix">
      <div class="logo">
        MY Task.app
      </div>
      <div class="login_logout">
        <% if logged_in? %>
        <% if current_user.admin %>
        <%= link_to "Admin", admin_users_path %>
        <% end %>
        <%= link_to "Profile", user_path(current_user.id) %>
        <%= link_to "Logout", session_path(current_user.id), method: :delete %>
        <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Login", new_session_path %>
        <% end %>
      </div>
    </header>
    <div class="wrapper clerfix">
      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>

    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local:true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %><%= t('view.error_number') %></h2>
      <ul>

      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="task_name">
      <%= form.label :task_name %>
      <p><%= form.text_field :task_name %></p>
    </div>
    <div class="content">
      <%= form.label :content %>
      <p><%= form.text_area :content %></p>
    </div>
    <div class="deadline">
      <%= form.label :deadline %>
      <p><%= form.date_field :deadline %></p>
    </div>
    <div class="priority">
      <%= form.label :priority %>
      <p><%= form.select :priority, {高: '高', 中: '中', 低: '低'}  %></p>
    </div>

    <% if action_name == 'new' %>

    <div class="status">
      <%= form.hidden_field :status, value: "未着手" %>
    </div>
    <div class="label">
    <% Label.all.each do |label| %>
    <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
    <label><%= label.name %></label>
    <% end %>
    </div>
    <%= form.submit  %>

    <% else %>
    <div class="status">
      <%= form.label :status %>
      <p><%= form.select :status, {未着手:'未着手', 着手中: '着手中', 完了: '完了'} %></p>
    </div>
    <div class="label">
    <% Label.all.each do |label| %>
    <%= form.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] %>
    <label><%= label.name %></label>
    <% end %>
    </div>
    <%= form.submit t('view.task_update') %>
    <% end %>
    <% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <h2><%= t('view.tasks_show') %></h2>
  <%= render "form" %>

  <%= link_to t('view.show'), task_path(@task.id) %>
  |
  <%= link_to t('view.index'), tasks_path %>
</div> 

app/views/tasks/index.html.erb
<h2><%= t('view.index') %></h2>
<%= link_to t('view.deadline_sort'), tasks_path(sort_deadline: "true") %>
<%= link_to t('view.priority_sort'), tasks_path(sort_priority: "true") %>
<%= form_with(model: @task, local: true, method: :get, url: tasks_path) do |form| %>
  <%= form.label :task_name_search, t('view.task_name_search') %>
  <%= form.text_field :task_name%>

  <%= form.label :status_search, t('view.status_search') %>
  <%= form.select :status, Task.statuses.keys, include_blank: true %>

  <%= form.label :label_search, t('view.label_search') %>
  <%= form.select :label_id, Label.pluck(:name, :id), include_blank: true %>

  <%= form.hidden_field :search, value: true %>

  <%= form.submit 'Search' %> <%= link_to 'Clear', tasks_path %>
<% end %>
<%= link_to t('view.new'), new_task_path, class: "btn btn-primary" %>
<%= link_to t('view.label_index'), labels_path, class: "btn btn-primary" %>

<table>
  <tr>
    <th class= 'th_task_name'><%= t('view.task_name') %></th>
    <th class= 'th_content'><%= t('view.content') %></th>
    <th class= 'th_created_at'><%= t('view.created_at') %></th>
    <th class= 'th_deadline'><%= t('view.deadline') %></th>
    <th class= 'th_status'><%= t('view.status') %></th>
    <th class= 'th_priority'><%= t('view.priority') %></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.task_name %></td>
    <td><%= task.content %></td>
    <td><%= task.created_at.strftime('%Y-%m-%d') %></td>
    <td><%= task.deadline.strftime('%Y-%m-%d') %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><div class="alert alert-warning" role="alert"><%= link_to t('view.show'), task_path(task.id),class: "alert-link" %></td>
    <td><div class="alert alert-info" role="alert"><%= link_to t('view.edit'), edit_task_path(task.id), class: "alert-link" %></div></td>
    <td><div class="alert alert-danger" role="alert"><%= link_to t('view.delete'), task_path(task.id), class: "alert-link",  method: :delete ,data: { confirm: "本当に削除してもよろしいですか？" } %></td>
  </tr>
<% end %>
</table>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<div class="container">
  <h2><%= t('view.tasks_new') %></h2>
  <%= render "form" %>

  <%= link_to t('view.index'), tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h2><%= t('view.tasks_show') %></h2>
  <p><%= t('view.task_name') %>: <%= @task.task_name %></p>
  <p><%= t('view.content') %>: <%= @task.content %></p>
  <p><%= t('view.deadline') %>: <%= @task.deadline.strftime('%Y-%m-%d') %></p>
  <p><%= t('view.priority') %>: <%= @task.priority %></p>
  <p><%= t('view.status') %>: <%= @task.status %></p>
  <p>関連づけたタグ:
    <% @task.labels.each do |label| %>
    <label><%= label.name %></label>
  <% end %>
  </p>

  <%= link_to t('view.show'), edit_task_path(@task.id) %>
  |
  <%= link_to t('view.index'), tasks_path %>
</div>

app/views/users/new.html.erb
<h2><%= t('view.user_new') %></h2>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <p><%= f.text_field :name %></p>

  <%= f.label :email %>
  <p><%= f.email_field :email %></p>

  <%= f.label :password %>
  <p><%= f.password_field :password %></p>

  <%= f.label :password_confirmation %>
  <p><%= f.password_field :password_confirmation %></p>

  <%= f.submit t('view.user_new') %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.name %>のページ</h2>

<p>メールアドレス: <%= @user.email %></p>

<%= link_to t('view.index'), tasks_path %>